export const MOVE_ENTITY = "MOVE_ENTITY";
export const FORCE_RENDER = "FORCE_RENDER";
export const TOGGLE_MOVEMENT_MODE = "TOGGLE_MOVEMENT_MODE";
export const END_TURN = "END_TURN";
export const TOGGLE_ATTACK_MODE = "TOGGLE_ATTACK_MODE";
